cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'awscli'
brew 'coreutils'
brew 'htop'
brew 'openssl'
brew 'python3'
brew 'spark'
brew 'tmux'
brew 'wget'
brew 'youtube-dl'
brew 'zsh-syntax-highlighting'

cask 'iterm2'
cask 'visual-studio-code'
cask 'vlc'
cask 'spotify'
cask 'spectacle'