#!/bin/bash

# Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install programs from Brewfile
brew tap Homebrew/bundle
brew bundle --verbose

# Set git up
git config --global user.username moggg
git config --global user.email mog@moop.net.au

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

exit 0